### ISSUE TITLE
GPU not detected and EER

### ISSUE THREAD

**Issue by ncoudray** [logicvay2010/TomoNet#21]
Hi - 

 I have a couple of questions:
1- any plan to support EER format in the future? I guess, meanwhile, can we start the process anywhere (like reconstruct tomograms separately and just start from the reconstructed tomo, or do foresee any trouble there?)
2- When running "AreTomo reconstruction", I get "ERROR - GPU is not detected" However, there is one and if I run "nvidia-smi" from the same terminal where the GUI is launched, it does detect the GPU.

Any suggestion?

Best,
Nicolas

**Comment by logicvay2010** [comment]
Thanks for trying out TomoNet!
1. The EER is not supported yet, its on the to do list, I will update here, if it is implement later. So, the current plan for the EER is that, you can start TomoNet from the motion corrected and averaged images.
2.  I cannot directly see what's the main issue here. I basically use the pytorch function to detect the gpu devices "detected_gpu_num = torch.cuda.device_count()". So, please make sure that the pytorch is installed. It could induced by the failure of torch recognizing the GPUs, or some driver version incompatibility? I can try to help if more information is provided.

Best,
Hui

**Comment by ncoudray** [comment]
Thanks Hui!
1- ok, thanks
2- I am actually using the SBGrid installation, but I will check. When I run the "Train Network" step, I also encounter some error which may be related - it gives

Tracebac```
k (most recent call last):
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/bin/train_picking_ts.py", line 79, in <module>
    metrics = network.train(data_dir, gpuID,
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/TomoNet/models/network_picking.py", line 63, in train
    trainer = pl.Trainer(
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/mamba/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 339, in insert_env_defaults
    return fn(self, **kwargs)
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/mamba/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 485, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/mamba/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 201, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/mamba/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 519, in _set_parallel_devices_and_init_accelerator
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: GPUAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].
```
Looks like a pytorch issue as well which may have the same cause as the one above

**Comment by logicvay2010** [comment]
I see, We do not have SBGrid setting in our lab, so have no exp for that setting.
I think it should related to the version of CUDA and the graphic card drive. 

Can you run any other software packages which requires GPU computation? 
If No, then this is a global issue of using GPU using python code, even though the "nvidia-smi" command runs okay. And you also need to make sure "nvcc --version" works as well. (nvcc: NVIDIA (R) Cuda compiler driver)
If Yes, then it is related to the code or the "conda" setting of TomoNet. Can you provide the output from both nvidia-smi and nvcc --version?

In my case, I have two setups that run okay for TomoNet GPU jobs. 
1. Cuda compilation tools, release 10.1, V10.1.243  &  NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8
2. Cuda compilation tools, release 11.8, V11.8.89    &  NVIDIA-SMI 550.50         Driver Version: 551.34         CUDA Version: 12.4 

FYI, the SBGrid use beta_03 version, I have just release beta_06 version. If you are able to install through git, the package has more or less update/improvement in most of the tabs. 

Best,
Hui

**Comment by logicvay2010** [comment]
For EER data, here is one alternative solution.
1. Transfer eer to tif using relion command, here is an example

      ls frames/*eer | while read eer; do bname=`basename $eer .eer`; relion_convert_to_tiff --i ${eer} --gain EER_GainReference.gain  --o ./ --eer_grouping 30; done

2.  Then you can use MotionCor2 to perform motion correction

3. rename the motion corrected micrograph filename (from step 2) into TomoNet friendly convention. (replace the bracket [ and ] to '_'), here is also an example of this conversion.

     ls *mrc | while read mrc; do newName=`ls $mrc | sed -r 's/[[]+/_/g' | sed -r 's/[]]+//g'`; mv $mrc $newName; done

Please do a mini batch test before apply to the entire dataset

**Comment by ncoudray** [comment]
Ah, thanks, that's useful to know!
