### ISSUE TITLE
Run Particle Expansion

### ISSUE THREAD

**Issue by ncoudray** [logicvay2010/TomoNet#22]
Hi  -

 When running the "Particle Expansion" job, I get tthe following error message: 

```
Traceback (most recent call last):
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/bin/sta_expand.py", line 99, in <module>
    tomo, search_param, target_cache_folder, peet_iter, end_signal_c = sta_peet_one(star_file, param_file, tomoName, cpus, first_round)
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/TomoNet/bin/sta_peet.py", line 223, in sta_peet_one
    com_read = open("{}/{}".format(tomo.staPath,com_file),"r")
FileNotFoundError: [Errno 2] No such file or directory: '/vast/gbhabha1/JHU_hot_data/home/ncoudra1/ClustersTest/SBGrid_packages/TomoNet_20240807/Expand/expand1_result/PW_BE_028_ts_018_4xBin_REC_1500volz_500alz/PW_BE_028_ts_018_4xBin_REC_1500volz_500alz-001.com'
Traceback (most recent call last):
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/TomoNet/process/bash_expand.py", line 29, in run
    subprocess.check_output(cmd, shell=True)
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/mamba/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/data/apps/extern/sbgrid/x86_64-linux/tomonet/beta_03/mamba/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sta_expand.py /vast/gbhabha1/JHU_hot_data/home/ncoudra1/ClustersTest/SBGrid_packages/TomoNet_20240807/Expand/expand1_result/tomograms1.star /vast/gbhabha1/JHU_hot_data/home/ncoudra1/ClustersTest/SBGrid_packages/TomoNet_20240807/Expand/newpick1.params PW_BE_028_ts_018_4xBin_REC_1500volz_500alz 7 12 8' returned non-zero exit status 1.
/data/apps/extern/sbgrid/share/capsules/lib/job.sh: line 126: 937862 Aborted                 (core dumped) "$SB_EXECFILE" "$@"
```
Any idea what could have gone wrong?
Thanks,
--Nicolas

**Comment by ncoudray** [comment]
ok - found the issue: it needs a certain version of imod.

So it ran, but the final GUI, the number of rounds and particles is not updated. From the log, looks like it should have been updated to 7 rounds and 307 particles 

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/a243e9a4-4356-456a-a8ba-874182a57335">

If I double click on "3dmod", you see it searches for a folder which does not exist directly under "Expand" (It actually exists but under another subfolder, Expand/expand1_result"

**Comment by logicvay2010** [comment]
Sorry for the late reply, I did not see your first message.
I see, you can set the "Select Expand Folder" to the "xx/expand1_result" to display the results under that folder. 
Another way to check this: go to the selected expand folder (as indicated in the tomograms1.star), and check if the xxx_final folder exists. All coords and angular results should be saved there
Please let me know if this does not works.

**Comment by ncoudray** [comment]
Ah, yes, that makes sense, thanks!
